project:
  type: website
  output-dir: ../docs

format:
 html:
   mainfont: "Century Schoolbook"

website:
  title: "Preguntas"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: bibliografia.qmd
        text: Bibliografía

theme:
  light: flatly
  dark: darkly